"""Domain schemas for root-cause hypotheses and investigation findings."""

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


# --- Enums ---
class HypothesisStatus(StrEnum):
    """Lifecycle status of a root-cause hypothesis as it is tested."""

    PROPOSED = "PROPOSED"
    TESTING = "TESTING"
    VERIFIED = "VERIFIED"
    REFUTED = "REFUTED"
    INCONCLUSIVE = "INCONCLUSIVE"


# --- Hypothesis Models ---
class Hypothesis(BaseModel):
    """A generated root-cause hypothesis explaining the incident."""

    id: str = Field(description="Unique hypothesis identifier")
    title: str = Field(description="Short summary of the hypothesis")
    description: str = Field(description="Detailed explanation of the potential failure mechanism")
    affected_component: str = Field(description="Service, database, or infrastructure component")
    confidence_score: float = Field(
        default=0.5, ge=0.0, le=1.0, description="Confidence score (0.0 to 1.0)"
    )
    status: HypothesisStatus = Field(default=HypothesisStatus.PROPOSED)
    supporting_evidence_ids: list[str] = Field(default_factory=list)
    refuting_evidence_ids: list[str] = Field(default_factory=list)
    verification_queries: list[str] = Field(
        default_factory=list, description="PromQL or LogQL queries needed to test this hypothesis"
    )
    missing_evidence_needed: list[str] = Field(
        default_factory=list,
        description="Specific metrics or logs required to substantiate this hypothesis",
    )
    reasoning_summary: str = Field(
        default="", description="Concise justification tied strictly to evidence"
    )
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class HypothesisVerificationResult(BaseModel):
    """Result of testing/verifying a hypothesis against telemetry."""

    hypothesis_id: str
    verified: bool
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str
    metrics_checked: list[str] = Field(default_factory=list)
    logs_checked: list[str] = Field(default_factory=list)
    missing_evidence_queries: list[str] = Field(default_factory=list)


# --- Root Cause Analysis ---
class RootCauseAnalysis(BaseModel):
    """Final root-cause determination for an incident."""

    primary_hypothesis_id: str
    summary: str
    root_cause_category: str = Field(
        description="e.g. HTTP_ERRORS, DEPENDENCY_FAILURE, RESOURCE_EXHAUSTION, LATENCY, UNKNOWN"
    )
    culprit_service: str
    contributing_factors: list[str] = Field(default_factory=list)
    supporting_evidence_ids: list[str] = Field(default_factory=list)
    technical_details: dict[str, Any] = Field(default_factory=dict)
    confidence: float = Field(ge=0.0, le=1.0)
    identified_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


# --- LLM Structured Output Response Models ---
class HypothesisCandidate(BaseModel):
    """Candidate hypothesis produced by LLM."""

    title: str = Field(description="Short descriptive hypothesis title")
    description: str = Field(description="Explanation of how and why the failure occurred")
    affected_component: str = Field(description="Specific service or component affected")
    confidence_score: float = Field(
        ge=0.0, le=1.0, description="Estimated confidence based solely on available evidence"
    )
    supporting_evidence_ids: list[str] = Field(
        default_factory=list, description="IDs of evidence items that support this hypothesis"
    )
    refuting_evidence_ids: list[str] = Field(
        default_factory=list, description="IDs of evidence items that contradict this hypothesis"
    )
    missing_evidence_needed: list[str] = Field(
        default_factory=list,
        description="PromQL or LogQL queries needed to confirm or rule out this hypothesis",
    )
    reasoning_summary: str = Field(
        default="", description="Concise justification referencing evidence IDs"
    )


class HypothesisGenerationResponse(BaseModel):
    """Structured response container for LLM hypothesis generation."""

    hypotheses: list[HypothesisCandidate] = Field(
        default_factory=list, description="List of candidate hypotheses generated by LLM"
    )


class HypothesisVerificationResponse(BaseModel):
    """Structured response container for LLM hypothesis verification.

    Evaluates exactly one pre-selected candidate hypothesis at a time (the caller picks the
    best candidate before prompting), so this response has no notion of an index into a list.
    """

    is_verified: bool = Field(
        default=False,
        description="True if evidence is strong enough to confirm as root cause",
    )
    confidence_score: float = Field(ge=0.0, le=1.0, description="Evaluated confidence score")
    reasoning: str = Field(
        default="", description="Concise evaluation summary referencing evidence"
    )
    additional_queries_needed: list[str] = Field(
        default_factory=list,
        description="Follow-up PromQL or LogQL queries if evidence is insufficient",
    )
