"""Remediation proposal and safety tier schemas."""

from datetime import UTC, datetime
from enum import IntEnum, StrEnum
from typing import Any

from pydantic import BaseModel, Field


# --- Safety Enums ---
class RemediationSafetyLevel(IntEnum):
    """Three-tier safety classification for incident remediations."""

    LEVEL_0_READ_ONLY = 0
    LEVEL_1_SAFE_AUTOMATIC = 1
    LEVEL_2_HUMAN_APPROVAL_REQUIRED = 2


class RemediationStatus(StrEnum):
    """Lifecycle status for remediation proposals."""

    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    ROLLED_BACK = "ROLLED_BACK"


# --- Remediation Actions & Proposals ---
class RemediationAction(BaseModel):
    """Discrete remediation step (recommendation only in v0.2)."""

    id: str
    name: str
    target_service: str
    safety_level: RemediationSafetyLevel
    action_type: str = Field(
        description="e.g. restart_service, rollback_deployment, reset_configuration, scale_replicas"
    )
    parameters: dict[str, Any] = Field(default_factory=dict)
    description: str


class RemediationProposal(BaseModel):
    """Complete remediation proposal containing one or more actions."""

    id: str
    incident_id: str
    title: str
    summary: str
    highest_safety_level: RemediationSafetyLevel
    requires_human_approval: bool = True
    status: RemediationStatus = RemediationStatus.PROPOSED
    actions: list[RemediationAction] = Field(default_factory=list)
    estimated_impact: str = ""
    rollback_plan: str = ""
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


# --- LLM Structured Output Models ---
class RemediationActionCandidate(BaseModel):
    """Action candidate proposed by LLM."""

    name: str = Field(description="Short name for the recommended action")
    target_service: str = Field(description="Service targeted by this action")
    safety_level: int = Field(
        default=2,
        ge=0,
        le=2,
        description="Safety level: 0 (read-only), 1 (safe automatic), 2 (requires human approval)",
    )
    action_type: str = Field(description="Action identifier e.g. reset_configuration, scale_pool")
    parameters: dict[str, Any] = Field(default_factory=dict)
    description: str = Field(description="Detailed explanation of what the action does")


class RemediationProposalResponse(BaseModel):
    """Structured proposal generated by LLM."""

    title: str = Field(description="Proposal title")
    summary: str = Field(description="Executive summary of why this remediation is proposed")
    actions: list[RemediationActionCandidate] = Field(
        default_factory=list, description="Recommended remediation actions"
    )
    estimated_impact: str = Field(
        default="", description="Expected outcome and recovery time after remediation"
    )
    rollback_plan: str = Field(
        default="", description="Steps to take if the remediation causes further degradation"
    )
